application: tarams-time-tracker-js-client
version: 1
runtime: python27
api_version: 1
threadsafe: true
module: default

default_expiration: "1m"

handlers:

- url: /static
  static_dir: static

- url: .*
  script: router.routes


libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: latest
