application: your-app-id
version: 1
runtime: python27
api_version: 1
threadsafe: true
module: default

default_expiration: "1m"

handlers:

- url: /(.*\.css)
  mime_type: text/css
  static_files: \1
  upload: (.*\.css)

- url: /(.*\.html)
  mime_type: text/html
  static_files: \1
  upload: (.*\.html)
  expiration: "10m"

- url: /(.*\.ico)
  mime_type: image/x-icon
  static_files: \1
  upload: (.*\.ico)

- url: /(.*\.js)
  mime_type: text/javascript
  static_files: \1
  upload: (.*\.js)

- url: /(.*\.json)
  mime_type: application/json
  static_files: \1
  upload: (.*\.json)

- url: /(.*\.m4v)
  mime_type: video/m4v
  static_files: \1
  upload: (.*\.m4v)

- url: /(.*\.mp4)
  mime_type: video/mp4
  static_files: \1
  upload: (.*\.mp4)

- url: /(.*\.(ogg|oga))
  mime_type: audio/ogg
  static_files: \1
  upload: (.*\.(ogg|oga))

- url: /(.*\.ogv)
  mime_type: video/ogg
  static_files: \1
  upload: (.*\.ogv)

- url: /(.*\.otf)
  mime_type: font/opentype
  static_files: \1
  upload: (.*\.otf)

- url: /(.*\.(svg|svgz))
  mime_type: images/svg+xml
  static_files: \1
  upload: (.*\.(svg|svgz))

- url: /(.*\.ttf)
  mime_type: font/truetype
  static_files: \1
  upload: (.*\.ttf)

- url: /(.*\.txt)
  mime_type: text/plain
  static_files: \1
  upload: (.*\.txt)

- url: /(.*\.webm)
  mime_type: video/webm
  static_files: \1
  upload: (.*\.webm)

- url: /(.*\.webp)
  mime_type: image/webp
  static_files: \1
  upload: (.*\.webp)

- url: /(.*\.woff)
  mime_type: application/x-font-woff
  static_files: \1
  upload: (.*\.woff)

- url: /(.*\.xml)
  mime_type: application/xml
  static_files: \1
  upload: (.*\.xml)

# image files
- url: /(.*\.(bmp|gif|ico|jpeg|jpg|png))
  static_files: \1
  upload: (.*\.(bmp|gif|ico|jpeg|jpg|png))

# audio files
- url: /(.*\.(mid|midi|mp3|wav))
  static_files: \1
  upload: (.*\.(mid|midi|mp3|wav))

# windows files
- url: /(.*\.(doc|exe|ppt|rtf|xls))
  static_files: \1
  upload: (.*\.(doc|exe|ppt|rtf|xls))

# compressed files
- url: /(.*\.(bz2|gz|rar|tar|tgz|zip))
  static_files: \1
  upload: (.*\.(bz2|gz|rar|tar|tgz|zip))

# site root
- url: /.*
  static_files: index.html
  upload: index.html
